// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qpxirspiunznxoyhuruj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFweGlyc3BpdW56bnhveWh1cnVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODcyMzgsImV4cCI6MjA2ODc2MzIzOH0.aW6XYb_PC4y_BRgN4rK18YxEG72YEdIXT-AUe8U0Trs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});